
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-dispatch
  namespace: hello-world
spec:
  maxReplicas: 4
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-dispatch
  targetCPUUtilizationPercentage: 80
