apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: hello-world-monitor
  namespace: hello-world
  labels:
    app: prometheus-operator
    release: prometheus-kubeaddons
spec:
  selector:
    matchLabels:
      app: hello-world-dispatch-primary
  namespaceSelector:
    matchNames:
    - hello-world
  podMetricsEndpoints:
  - port: web
    path: /actuator/prometheus
